name: CloudixNetwork
version: '${project.version}'
main: ru.hogeltbellai.CloudixNetwork.CNPluginSpigot
api-version: 1.16
author: HogeltBellai

commands:
  msg:
  ban:
  mute:
  unban:
  ignore:
  speed:
  stp:
  cloudix: