CREATE TABLE IF NOT EXISTS users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL,
    pix INT(11) NOT NULL DEFAULT '0',
    exp INT(11) NOT NULL DEFAULT '0',
    online INT(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    UNIQUE KEY usernames (username) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED;

CREATE TABLE IF NOT EXISTS users_meta (
    userid INT(11) NOT NULL,
    `key` VARCHAR(30) NOT NULL,
    value VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (userid, `key`),
    FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED;

CREATE TABLE IF NOT EXISTS bans (
    id INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL COLLATE utf8mb4_general_ci,
    end_time BIGINT(20) NOT NULL,
    start_time BIGINT(20) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    banned_by VARCHAR(255) DEFAULT NULL,
    status TINYINT(4) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `users` (`username`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED;

CREATE TABLE IF NOT EXISTS mutes (
    id INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL COLLATE utf8mb4_general_ci,
    end_time BIGINT(20) NOT NULL,
    start_time BIGINT(20) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    muted_by VARCHAR(255) DEFAULT NULL,
    status TINYINT(4) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `users` (`username`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED;